<!--
The #page-top ID is part of the scrolling feature.
The data-spy and data-target are part of the built-in Bootstrap scrollspy function.
-->


<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<!--=== Style Switcher ===-->    
<i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
<div class="style-switcher animated fadeInRight">
    <div class="style-swticher-header">
        <div class="style-switcher-heading">Style Switcher</div>            
        <div class="theme-close"><i class="icon-close"></i></div>
    </div>

    <div class="style-swticher-body">
        <!-- Theme Colors -->
        <div class="style-switcher-heading">Theme Colors</div>
        <ul class="list-unstyled">
            <li class="theme-default" data-style="default" data-header="light"></li>
            <li class="theme-blue" data-style="blue" data-header="light"></li>
            <li class="theme-orange" data-style="orange" data-header="light"></li>
            <li class="theme-red" data-style="red" data-header="light"></li>
            <li class="theme-light" data-style="light" data-header="light"></li>
            <li class="theme-purple last" data-style="purple" data-header="light"></li>
            <li class="theme-aqua theme-active" data-style="aqua" data-header="light"></li>
            <li class="theme-brown" data-style="brown" data-header="light"></li>
            <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
            <li class="theme-light-green" data-style="light-green" data-header="light"></li>
            <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
            <li class="theme-teal last" data-style="teal" data-header="light"></li>
        </ul>          
    </div>
</div><!--/style-switcher-->
<!--=== End Style Switcher ===-->


<!--=== Header ===-->
<nav class="one-page-header navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="menu-container page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="#intro">
                <span>Faal Kor.Fut.</span> <span>Hak. Ve Gözl.</span>
                <!-- <img src="assets/img/logo1.png" alt="Logo"> -->
            </a>

            <!-- multilanguage, help ve login linkleri -->
            <!-- Topbar -->
            <div class="topbar">
                <ul class="loginbar pull-right">
                    <!--<li class="hoverSelector">
                        <a><?php echo $this->translate('Languages') ?>  </a>
                        <i class="fa fa-globe"></i>
                        <ul class="languages hoverSelectorBlock">
                        </ul>
                    </li>
                    <li class="topbar-devider"></li>   
                    <li><a href="page_faq.html"><?php echo $this->translate('Help') ?></a></li>  
                    <li class="topbar-devider"></li>-->   
                    <li><a href="/ref/TRF/login"><?php echo $this->translate('Log in') ?> </a></li>   
                </ul>
            </div>
            <!-- End Topbar -->

        </div>
<!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <div class="menu-container">
                <ul class="nav navbar-nav">
                    <li class="page-scroll home">
                        <a href="#body">Intro</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#news"><?php echo $this->translate('News') ?></a>
                    </li>  
                    <li class="page-scroll">
                        <a href="#publish">Kural / Mekanik Kaynaklar</a>
                    </li>                    

                    <li class="page-scroll">
                        <a href="#contact"><?php echo $this->translate('Contact Us') ?></a>
                    </li>
                </ul>
            </div>
        </div>    
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
<!--=== End Header ===-->

<!-- Intro Section -->
<section id="intro" class="intro-section">
    <div class="fullscreenbanner-container">
        <div class="fullscreenbanner">
            <ul>
                <!-- SLIDE 1 -->
                <li data-transition="curtain-1" data-slotamount="5" data-masterspeed="700" data-title="Slide 1">
                    <!-- MAIN IMAGE -->
                    <!--<img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/sliders/revolution/bg1.jpg') ?>" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">-->
                    <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/sliders/modified_sliders/american-football2.jpg') ?>" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">

                    <!-- LAYERS -->
                    <div class="tp-caption rs-caption-1 sft start" style="color:#fff;font-weight: bolder;"
                         data-x="center"
                         data-hoffset="0"
                         data-y="200"
                         data-speed="800"
                         data-start="2000"
                         data-easing="Back.easeInOut"
                         data-endspeed="300">
                         Faal Korumalı Futbol Hakem Ve Gözlemcileri  
                             <?php /*echo $this->translate('OSB IMALAT') ?>  <?php echo $this->translate(' Project') ?>
                             <?php echo $this->uri*/ ?>
                    </div>

                    <!-- LAYER -->
                    <div class="tp-caption rs-caption-2 sft"
                         data-x="center"
                         data-hoffset="0"
                         data-y="300"
                         data-speed="1000"
                         data-start="3000"
                         data-easing="Power4.easeOut"
                         data-endspeed="300"
                         data-endeasing="Power1.easeIn"
                         data-captionhidden="off"
                         style="z-index: 6;color:#fff;font-weight: bolder;">
                        Türkiye'de,Türkiye Rugbi Federasyonu(TRF) ve Üniversiteler Spor Ligi(Ünilig)</br> 
                        Avrupa'da, IFAF bünyesinde gerçekleştirilen </br> 
                        Korumalı Futbol Müsabakalarına Hakem ve Gözlemci Ekiplerimizle Katılmaktayız.
                        <?php /*echo $this->translate('Follow Development')*/ ?><br>
                        <?php /*echo $this->translate('Opening SMEs manufacturing capabilities to the customers from all over the world')*/ ?><!--We minimize the gap between technology and its audience.-->
                    </div>

                    <!-- LAYER -->
                    <div class="tp-caption rs-caption-3 sft"
                         data-x="center"
                         data-hoffset="0"
                         data-y="460"
                         data-speed="800"
                         data-start="3500"
                         data-easing="Power4.easeOut"
                         data-endspeed="300"
                         data-endeasing="Power1.easeIn" 
                         data-captionhidden="off"
                         style="z-index: 6">
                        <span class="page-scroll"><a href="#about" class="btn-u btn-brd btn-brd-hover btn-u-light"><?php echo $this->translate('Learn more') ?></a></span>
                        <!--<span class="page-scroll"><a href="#portfolio" class="btn-u btn-brd btn-brd-hover btn-u-light"><?php echo $this->translate('Our Job') ?>  </a></span>-->
                    </div>
                </li>
            </ul>
            <div class="tp-bannertimer tp-bottom"></div>
            <div class="tp-dottedoverlay twoxtwo"></div>
        </div>
    </div>
</section>
<!-- End Intro Section -->


    

        <!-- Colorful Service Blocks -->
    <section id='publish' class="publish-section"  >
        <div class="container-fluid"> 
        <div class="title-v1">
            <h2><?php echo $this->translate('Latest News') ?></h2>
            <p>Faal Korumalı Futbol Hakem Ve Gözlemcileri <strong>faaliyet ve düzenlemeleri</strong>  ile ilgili son haberler ve bilgilendirmeler, <br>
                <strong>detaylı duyuru ve haberler</strong>  için <a>Faal Korumalı Futbol ve Gözlemcileri Derneği Ana Sayfası</a> linkine tıklayınız.</p>
        </div>
        
        <div class=" no-gutter equal-height-columns margin-bottom-10 ">
            <div class="col-sm-4">
                <div class="service-block service-block-purple no-margin-bottom content equal-height-column" style="height: 239px;">
                    <i class="icon-custom icon-md rounded icon-color-light icon-line icon-book-open"></i>
                    <h2 class="heading-md font-light">Hakem Mekanik Kitabı</h2>
                    <p class="no-margin-bottom font-light">Kural bilgisi kadar mekanik bilgiside sahada önemlidir. Mekanik bilmeden tam ve doğru kural uygulamalarında bulunamayız.</p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="service-block service-block-red no-margin-bottom content equal-height-column" style="height: 239px;">
                    <i class="icon-custom icon-md rounded icon-color-light icon-line icon-book-open"></i>
                    <h2 class="heading-md font-light">Kural Kitabı</h2>
                    <p class="no-margin-bottom font-light">Türkçe kural kitabımız güncellenmiş ve editör kontrolünden geçirilerek 2016-2017 sezonuna hazı hale getirilmiştir.</p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="service-block service-block-aqua no-margin-bottom content equal-height-column" style="height: 239px;">
                    <i class="icon-custom icon-md rounded icon-color-light icon-line icon-book-open"></i>
                    <h2 class="heading-md font-light">İngilizce Kural Kitabı</h2>
                    <p class="no-margin-bottom font-light">Orijinal kural kitabından yararlanmak isteyenler için kaynakça</p>
                </div>
            </div>
        </div> 
            
        </div>
    </section>
    <!-- End Colorful Service Blocks -->



<!-- News Section -->
<section id="news" class="news-section">
    <div class="container content-lg">   
        <div class="title-v1">
            <h2><?php echo $this->translate('Latest News') ?></h2>
            <p>Faal Korumalı Futbol Hakem Ve Gözlemcileri <strong>faaliyet ve düzenlemeleri</strong>  ile ilgili son haberler ve bilgilendirmeler, <br>
                <strong>detaylı duyuru ve haberler</strong>  için <a>Faal Korumalı Futbol ve Gözlemcileri Derneği Ana Sayfası</a> linkine tıklayınız.</p>
        </div>

        <div class="row news-v1">
            <div class="col-md-4 md-margin-bottom-40">
                <div class="news-v1-in">
                    <img class="img-responsive" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/contents/mekanik_news.jpg') ?>" alt="">
                    <h3><a href="http://tfkfhgd.org/hakem-mekanikleri-kitabi/">Korumalı Futbol Hakem Mekanikleri Kitabı Versiyon 1 Yayınlandı</a></h3>
                    <p>Mekanik Kitabı yıl içerisinde elden geçirilerek IFAF Mekanik kitabına uygun hale getirilecek ve versiyonlar halinde yayınlanacaktır.</p>
                    <ul class="list-inline news-v1-info">
                        <li><!--<span>By</span>--> <a href="http://tfkfhgd.org/">Faal Korumalı Futbol Hak. ve Göz. Der.</a></li>
                        <li>|</li>
                        <li><i class="fa fa-clock-o"></i> 29 Kasım, 2016</li>
                        <li class="pull-right"><a href="#"><i class="fa fa-comments-o"></i> 0</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 md-margin-bottom-40">
                <div class="news-v1-in">
                    <img class="img-responsive" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/contents/kurul_news.jpg') ?>" alt="">
                    <h3><a href="#">2.Olağan Genel Kurulumuz Yapıldı</a></h3>
                    <p>Olağan genel kurulumuz üyelerimizin katılımıyla gerçekleştirildi.</p>
                    <ul class="list-inline news-v1-info">
                        <li><span>By</span> <a href="http://tfkfhgd.org/">Faal Korumalı Futbol Hak. ve Göz. Der.</a></li>
                        <li>|</li>
                        <li><i class="fa fa-clock-o"></i> 13 Kasım, 2016</li>
                        <li class="pull-right"><a href="http://tfkfhgd.org/2-inci-olagan-genel-kurul-secimimizden-kareler/"><i class="fa fa-comments-o"></i> 0</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="news-v1-in">
                    <img class="img-responsive" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/contents/aday_news.jpg') ?>" alt="">
                    <h3><a href="#">Korumalı Futbol Hakem Aday Kursu</a></h3>
                    <p>Korumalı Futbol Hakem adayları Ankara, İzmir ve İstanbul'da toplandılar.</p>
                    <ul class="list-inline news-v1-info">
                        <li><span>By</span> <a href="http://tfkfhgd.org/">Faal Korumalı Futbol Hak. ve Göz. Der.</a></li>
                        <li>|</li>
                        <li><i class="fa fa-clock-o"></i> 10 Ekim, 2016</li>
                        <li class="pull-right"><a href="http://tfkfhgd.org/korumali-futbol-aday-hakem-kursu-ankara-istanbul-izmir/"><i class="fa fa-comments-o"></i> 0</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="parallax-twitter parallaxBg">
            <div class="container parallax-twitter-in">
                <div class="margin-bottom-30">
                    <i class="icon-custom rounded-x icon-bg-blue fa fa-rss">
                        <!--<img width src='<?php echo $this->basePath('onyuz/One-Page/assets/img/logo/dernek_logo.png') ?>'></img>-->
                    </i>
                </div>

                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <ul class="list-unstyled owl-twitter-v1">
                            <li class="item">
                                <p>10-11 Aralık 2016 haftnın hakemleri açıklandı <a href="http://tfkfhgd.org/10-11-aralik-2016-haftanin-hakemleri-aciklandi/">Tam Liste</a><p>
                                    <span><a href="http://tfkfhgd.org/">Faal Korumalı Futbol Hak. ve Göz. Der.</a></span>
                            </li>
                            <li class="item">
                                <p>YouTube Eğitim Kanalımız<a href="https://www.youtube.com/channel/UCR96_fOWOHKCBH2fV6UrDBA"> Link </a> Canlı yayın ve tüm eğitimlerimizi kanalımızdan takip edebilirsiniz </p>
                                <span><a href="http://tfkfhgd.org/">Faal Korumalı Futbol Hak. ve Göz. Der.</a></span>
                            </li>
                            <!--<li class="item">
                                <p>New 100% Free Stock Photos. Every. Single. Day. Everything you need for your creative projects. <a href="#">http://publicdomainarchive.com</a></p>
                                <span><a href="http://tfkfhgd.org/">Faal Korumalı Futbol Hak. ve Göz. Der.</a></span>
                            </li>-->
                        </ul>
                    </div>
                </div>
            </div>  
        </div>
</section>
<!-- End News Section -->



<!-- Contact Section -->
<section id="contact" class="contacts-section">
    <div class="container content-lg">
        <div class="title-v1">
            <h2><?php echo $this->translate('Contact us') ?><!--Contact Us--></h2>
            <p><?php echo $this->translate('') ?></p>
        </div>

        <div class="row contacts-in">
            <div class="col-md-6 md-margin-bottom-40">
                <ul class="list-unstyled">
                    <li><i class="fa fa-home"></i> </li>
                    <li><i class="fa fa-phone"></i>  </li>
                    <li><i class="fa fa-fax"></i> </li>  
                    <li><i class="fa fa-envelope"></i> <a href=""></a></li>
                    <li><i class="fa fa-globe"></i> <a href=""></a></li>
                </ul>
            </div>

            <div class="col-md-6">
                <form action="http://htmlstream.com/preview/unify-v1.8/One-Page/assets/php/sky-forms-pro/demo-contacts-process.php" method="post" id="sky-form3" class="sky-form contact-style">
                    <fieldset>
                        <label><?php echo $this->translate('Name') ?><!--Name--></label>
                        <div class="row">
                            <div class="col-md-7 margin-bottom-20 col-md-offset-0">
                                <div>
                                    <input type="text" name="name" id="name" class="form-control">
                                </div>
                            </div>
                        </div>

                        <label><?php echo $this->translate('Email') ?> <!--Email--> <span class="color-red">*</span></label>
                        <div class="row">
                            <div class="col-md-7 margin-bottom-20 col-md-offset-0">
                                <div>
                                    <input type="text" name="email" id="email" class="form-control">
                                </div>
                            </div>
                        </div>

                        <label><?php echo $this->translate('Message')?></label>
                        <div class="row">
                            <div class="col-md-11 margin-bottom-20 col-md-offset-0">
                                <div>
                                    <textarea rows="8" name="message" id="message" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>

                        <p><button type="submit" class="btn-u btn-brd btn-brd-hover btn-u-dark"><?php echo $this->translate('Send Message') ?><!--Send Message--></button></p>
                    </fieldset>

                    <div class="message">
                        <i class="rounded-x fa fa-check"></i>
                        <p>Mesajınız başarıyla gönderildi!</p>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="copyright-section">
        <p><?php echo $this->translate('Copyright') ?> &copy;  2016<!--2015 &copy; All Rights Reserved. Unify Theme by-->   
                <a target="_blank" href="https://twitter.com/OSBImalat">Faal Korumalı Futbol Hakem Ve Gözlemcileri</a>
        </p>
        <ul class="social-icons">  
            <li><a href="https://www.facebook.com/" data-original-title="Facebook" class="social_facebook rounded-x js-sociaLinks js-sociaLinks"></a></li>
            <li><a href="https://twitter.com/" data-original-title="Twitter" class="social_twitter rounded-x js-sociaLinks"></a></li>
            <li><a href="https://plus.google.com/" data-original-title="Goole Plus" class="social_googleplus rounded-x js-sociaLinks"></a></li>
            <li><a href="https://www.instagram.com/" data-original-title="Instagram" class="social_instagram rounded-x js-sociaLinks"></a></li>
            <li><a href="https://www.linkedin.com/" data-original-title="Linkedin" class="social_linkedin rounded-x js-sociaLinks"></a></li>
            <!--<li><a href="https://www.instagram.com/OSBImalat/" data-original-title="Instagram" class="social_instagram rounded-x"></a></li>-->

        </ul>
        <span class="page-scroll"><a href="#intro"><i class="fa fa-angle-double-up back-to-top"></i></a></span>
    </div>
</section>    
<!-- End Contact Section -->

