<!DOCTYPE html> 

<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input> 
<input id="pktemp" type="hidden" value=""></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<body>
    <!--=== Style Switcher ===-->    
    <i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
    <div class="style-switcher animated fadeInRight">
        <div class="style-swticher-header">
            <div class="style-switcher-heading"><?php echo $this->translate('Style Switcher') ?></div>            
            <div class="theme-close"><i class="icon-close"></i></div>
        </div>

        <div class="style-swticher-body">
            <!-- Theme Colors -->
            <div class="style-switcher-heading"><?php echo $this->translate('Theme Colors') ?></div>
            <ul class="list-unstyled">
                <li class="theme-default theme-active" data-style="default" data-header="light"></li>
                <li class="theme-blue" data-style="blue" data-header="light"></li>
                <li class="theme-orange" data-style="orange" data-header="light"></li>
                <li class="theme-red" data-style="red" data-header="light"></li>
                <li class="theme-light" data-style="light" data-header="light"></li>
                <li class="theme-purple last" data-style="purple" data-header="light"></li>
                <li class="theme-aqua" data-style="aqua" data-header="light"></li>
                <li class="theme-brown" data-style="brown" data-header="light"></li>
                <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
                <li class="theme-light-green" data-style="light-green" data-header="light"></li>
                <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
                <li class="theme-teal last" data-style="teal" data-header="light"></li>
            </ul>

            <!-- Theme Skins -->
            <div class="style-switcher-heading"><?php echo $this->translate('Theme Skins') ?></div>
            <div class="row no-col-space margin-bottom-20 skins-section">
                <div class="col-xs-6">
                    <button data-skins="default" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn handle-skins-btn">Light</button>
                </div>
                <div class="col-xs-6">
                    <button data-skins="dark" class="btn-u btn-u-xs btn-u-dark btn-block skins-btn"><?php echo $this->translate('Dark') ?></button>
                </div>
            </div>                  
        </div>
    </div><!--/style-switcher-->
    <!--=== End Style Switcher ===-->   

    <!--=== Content Part ===-->         
    <div class="container">
        <!--Reg Block-->
        <div class="reg-block">
            <form method="post" id="userLoginForm">
                <div class="reg-block-header">
                    <h2>Lütfen Giriş Yapınız</h2>
                    <!--<ul class="social-icons text-center">
                        <li><a class="rounded-x social_facebook" data-original-title="Facebook" href="#"></a></li>
                        <li><a class="rounded-x social_twitter" data-original-title="Twitter" href="#"></a></li>
                        <li><a class="rounded-x social_googleplus" data-original-title="Google Plus" href="#"></a></li>
                        <li><a class="rounded-x social_linkedin" data-original-title="Linkedin" href="#"></a></li>
                    </ul>-->
                    <a href="/ref/TRF" class="btn btn-block "><img style="height:120px;" src="/onyuz/One-Page/assets/img/logo/dernek_logo.png"> <!--<img style="height:50px;" src="/onyuz/One-Page/assets/img/logo/header_logo.png">--> </a>
                    <!--<a href="/ostim/sanalfabrika" class="btn btn-block "><img style="height:50px;" src="/dist/img/ostim_logo_en.png"> <img style="height:50px;" src="/onyuz/One-Page/assets/img/logo/header_logo.png"> </a>-->
                    <p>Faal Korumalı Futbol Hakem Ve Gözlemcileri</p>            
                </div>

                <div class="input-group margin-bottom-20">
                    <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                    <input type="text" id="eposta" name="eposta" class="form-control validate[required,custom[email]]" placeholder="E-Posta">
                </div>
                <div class="input-group margin-bottom-20">
                    <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                    <input type="password" id="sifre" name="sifre" class="form-control validate[required,minSize[8],maxSize[20]]" data-prompt-position="bottomLeft" placeholder="Şifre">
                </div>
                <hr>

                <!--<div class="checkbox">
                    <label>
                        <input type="checkbox"> 
                        <p><?php echo $this->translate("Always stay signed in") ?></p>
                    </label>            
                </div>-->

                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <button type="submit" class="btn-u btn-block"><?php echo $this->translate("Log In") ?></button>
                    </div>
                </div>
            </form>
        </div>
        <!--End Reg Block-->
    </div><!--/container-->
    <!--=== End Content Part ===-->
</body>

</html>